### PR TITLE
deps: Update criterion to 0.5

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Review by fitzgen — APPROVED** [review]
Thanks! Does this version of criterion still produce HTML reports by default, or do we need to enable a feature now?

**Comment by waywardmonkeys** [comment]
I will get back to you about that (in 18-36 hours as I'm about to disappear for 16 hours or so). There's also the issue of the failed MSRV build. Arguably, the MSRV build shouldn't compile everything, but only the core library?

**Comment by waywardmonkeys** [comment]
@fitzgen Okay, I added `html_reports` to the features for it.

That leaves MSRV. `anstyle` requires 1.64, you want 1.63 (but the `rust-version` in the `Cargo.toml` is still set to 1.60). Would you want to bump to 1.64 or 1.66? Or not compile tests for MSRV?

**Comment by fitzgen** [comment]
The tests should run for the MSRV, but benchmarks don't need to. I think cargo compiles all dev deps for tests though.

I think it is fine to bump the MSRV. Would you mind updating the `rust-version` in `Cargo.toml`, CI, and the `README`'s documentation as well?

Thanks @waywardmonkeys!

**Comment by waywardmonkeys** [comment]
Now `anstyle` wants 1. 70 or later ... I'm not going to chase this as it is somewhat ridiculous.

**Comment by fitzgen** [comment]
Closing old pull requests.

**Pull request closed without merging**
