### PR TITLE
Use `#![doc = include_str!("../README.md")]` instead of `cargo readme`

### PR DESCRIPTION
**Pull request by fitzgen**
This makes it easier for contributors, since they don't need to install an
external tool anymore. Basically every contributor would forget to do this and
it was a major speed bump to contributing to this crate.

Also there aren't checked-in build artifacts in the repo anymore.

### CODE REVIEW

**Comment by fitzgen** [comment]
This might require bumping the MSRV

**Comment by konsumlamm** [comment]
Can this be merged soon? I'd like to improve the readme / doc comments, but I'd rather wait for this PR, since it also changes the readme.

**Comment by fitzgen** [comment]
Just waiting on https://github.com/fitzgen/bumpalo/issues/131 so that we can roll all MSRV bumps together at once.

If you want to help push that forward, since it seems to have stalled, then that would help speed up this PR landing.

**Comment by pointerless** [comment]
This seems to have caused issues with building on my system:
```
    Compiling bumpalo v3.9.0
  error: unexpected token: 'include_str'
   --> /home/pointerless/.cargo/registry/src/github.com-1ecc6299db9ec823/bumpalo-3.9.0/src/lib.rs:1:10
    |
  1 | #![doc = include_str!("../README.md")]
    |          ^^^^^^^^^^^
  
  error: aborting due to previous error
  
  error: could not compile 'bumpalo'.
```

**Comment by fitzgen** [comment]
@pointerless are you using Rust >= 1.54?

**Comment by pointerless** [comment]
@fitzgen I have just tried again with the rustup bundled cargo and the issue is gone. I must've been using an older version. Cheers

**Pull request merged**
